### ISSUE TITLE
Recovered cases

### ISSUE THREAD

**Issue by AntoineSoetewey** [RamiKrispin/coronavirus_dashboard#11]
Dear Rami, do you expect to edit the code given that the recovered cases have been removed from the dataset since March 23rd?

**Comment by RamiKrispin** [comment]
Hi @AntoineSoetewey, recovered cases were added back to the raw data. The data on the dashboard was updated and I will push additional changes to the dashboard in the coming days

**Comment by AntoineSoetewey** [comment]
Thanks!
