### ISSUE TITLE
update data

### ISSUE THREAD

**Issue by ismaeljoseph** [RamiKrispin/coronavirus_dashboard#12]
Case for haiti is not update.

Can you help me install the script and use Health Ministry to update info for Haiti. 

And also I want Haiti to be the first country that appear on the map, since I wanted to informed them first about the spreading of the virus.

**Comment by RamiKrispin** [comment]
The data source for this dashboard is John Hopkins's repo. If Haiti is not there you should open an issue on their page with the information of the cases.

For changes in the script for individual countries, I would recommend checking examples of people that modify the dashboard to a specific country:

https://rpubs.com/LupuAlexandru/584889
