### ISSUE TITLE
Include the last update date in the dashboard

### ISSUE THREAD

**Issue by bbolingbroke** [RamiKrispin/coronavirus_dashboard#13]
Please include the datetime that the data was last updated on the dashboard.

**Comment by AntoineSoetewey** [comment]
`max(coronavirus$date)` will give the last date available in the dataset if I remember well.

**Comment by RamiKrispin** [comment]
Hi @bbolingbroke 
I added last update date to the main plot on the [summary](https://ramikrispin.github.io/coronavirus_dashboard/) tab and to the [about](https://ramikrispin.github.io/coronavirus_dashboard/#about) tab

**Comment by bbolingbroke** [comment]
Thanks!
