### ISSUE TITLE
Provide a guide of how to run the dashboard

### ISSUE THREAD

**Issue by MoRadwan74** [RamiKrispin/coronavirus_dashboard#17]
First of all, I want to truly thank you, for this marvelous work but I have a small issue that is encountered by me and maybe by others also. I simply can't run the project to see the results on R studio or the browser or something.

I'm not an R developer but the dashboard looks very useful to be used and customized and I believe this is your intention when you posted this project to the open-source community.

So it will be great to provide a small section of how to install R and run the dashboard.

Cheers.

**Comment by AntoineSoetewey** [comment]
If I may, here is a [guide](https://www.statsandr.com/blog/how-to-create-a-simple-coronavirus-dashboard-specific-to-your-country-in-r/ ) I wrote on how to create a similar dashboard for your country based on Rami’s dashboard. Hope this helps.

**Comment by MoRadwan74** [comment]
@AntoineSoetewey Your article seems very promising to be helpful indeed. I will go through it step by step and give it a real try. Thank you, Antoine.
