### ISSUE TITLE
Strange data for Sweden

### ISSUE THREAD

**Issue by ddundovic** [RamiKrispin/coronavirus_dashboard#19]
Why is the number of recovered cases =0 for Sweden?
Still in May it wasn't so ...

**Comment by RamiKrispin** [comment]
The data on the dashboard is based on the **coronavirus** package which source the data from John Hopkins Covid19 tracking repository. I checked the raw data, and it is 0 for Sweden. Sweden does not provide this information, here is an issue about it on John Hopkins repo:
https://github.com/CSSEGISandData/COVID-19/issues/2618

Here is the raw data:
https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv
