### ISSUE TITLE
Warning messages

### ISSUE THREAD

**Issue by liamxg** [RamiKrispin/coronavirus_dashboard#22]
this is great and I never see this before, and so nice project, and  could you please figure the following below, thanks.

plotly::plot_ly(y = ~ round(100 * recover_rate, 1),
                  x = ~ round(100 * death_rate, 1),
                  size = ~  log(confirmed),
                  sizes = c(5, 70),
                  type = 'scatter', mode = 'markers',
                  color = ~ country,
                  marker = list(sizemode = 'diameter' , opacity = 0.5),
                  hoverinfo = 'text',
                  text = ~paste("</br>", country, 
                                "</br> Confirmed Cases: ", confirmed,
                                "</br> Recovery Rate: ", paste(round(100 * recover_rate, 1), "%", sep = ""),
                                "</br> Death Rate: ",  paste(round(100 * death_rate, 1), "%", sep = ""))
                 ) %>%
  plotly::layout(title = "Recovery / Death Ratio (Countries with More than 20,000 Cases)",
    yaxis = list(title = "Recovery Rate", ticksuffix = "%"),
                xaxis = list(title = "Death Rate", ticksuffix = "%", 
                             dtick = 1, 
                             tick0 = 0),
                hovermode = "compare")

Warning messages:
1: In RColorBrewer::brewer.pal(N, "Set2") :
  n too large, allowed maximum for palette Set2 is 8
Returning the palette you asked for with that many colors

2: In RColorBrewer::brewer.pal(N, "Set2") :
  n too large, allowed maximum for palette Set2 is 8
Returning the palette you asked for with that many colors

**Comment by RamiKrispin** [comment]
@LiXingguangBrandonStark are you referring to the warning messages?

**Comment by liamxg** [comment]
Dear @RamiKrispin ,

Yes, the the warning messages.

Best,
Liam

**Comment by RamiKrispin** [comment]
The working message is a result of exceeding the number of colors available in the color palette you are using. For example, using a color palette of 8 colors, and you are trying to get 9 colors.

**Comment by liamxg** [comment]
Dear @RamiKrispin ,

Thanks for the clarification! I see now that the issue is related to exceeding the available colors in the palette.

Best,
Liam
