### ISSUE TITLE
How do you set up the Autoupdate Dashboard?

### ISSUE THREAD

**Issue by max-torch** [RamiKrispin/coronavirus_dashboard#27]
From looking at the commit history, I can see that daily commits are being pushed to update the data on the dashboard website. What I would like to ask is: how do you set this up to happen automatically, and do you need to have a computer at home that is always turned on during the update schedule to make sure it autoupdates?

I like your portfolio website and I followed you on GitHub.

**Comment by RamiKrispin** [comment]
Hi @max-torch,

I am using Github actions for the automation, here is an example:
https://github.com/RamiKrispin/coronavirus_dashboard/blob/master/.github/workflows/data_refresh.yml

Basically, it triggers a job every 6 hours to run a code to update the dashboard. I used docker to set the environment. They have great documentation about how to use it over here:
 https://github.com/features/actions
