### ISSUE TITLE
daily_confirmed takes uncleaned data (from coronavirus) so fails on "China" vs. "Mainland China"

### ISSUE THREAD

**Issue by benstanbury** [RamiKrispin/coronavirus_dashboard#5]
```
daily_confirmed <- coronavirus %>%
  dplyr::filter(type == "confirmed") %>%
  dplyr::mutate(country = dplyr::if_else(Country.Region == "China", 
                                         "China", 
                                         "Rest of the World"))
```
Otherwise runs fine. Great work btw!

**Comment by RamiKrispin** [comment]
Thanks @benstanbury, 

You are probably using an older version. There was a change in the raw data for the country labels few days ago and it was updated on the dashboard as well - [here](https://github.com/RamiKrispin/coronavirus_dashboard/commit/9a7be6466c40782540288bb8de91d433833c22ae#diff-f06390acc60c07aadad857caace0f767)

Best,
Rami

**Comment by benstanbury** [comment]
That's great - thanks Rami. If I download the data direct from your Github repo then everything works perfectly. The version on the CRAN was a little out of date.

**Comment by RamiKrispin** [comment]
Yes, you will have to install the dev version to get the most recent version, some changes have been made in the structure of the data.

**Comment by RamiKrispin** [comment]
I Added function to update the data from the Github version (if available). You will have to install the Github version and run `update_datasets()` to check for updates
