### ISSUE TITLE
Facing problem running flexdashboard

### ISSUE THREAD

**Issue by sotirismargaritis** [RamiKrispin/coronavirus_dashboard#6]
Good evening i face this problem can someone may tell me what happens?

![problem](https://user-images.githubusercontent.com/62388562/77078040-bbb48100-69fe-11ea-8854-eb0dbb0c2c1d.PNG)

**Comment by RamiKrispin** [comment]
It seems like labeling issue, it can't find `China`. So my guess that you are using old version of the **coronavirus** package (which used `China Midland`). To fix this the most recent version of the **coronavirus** package from Github and try to run it again.

You can use `devtools::install_github("RamiKrispin/coronavirus")` to install it

**Comment by sotirismargaritis** [comment]
Thank you so much it worked.

**Comment by sotirismargaritis** [comment]
Thank you very much. If i want to update daily my data i must use this link ?devtools::install_github("RamiKrispin/coronavirus")

**Comment by RamiKrispin** [comment]
I pushed yesterday a new function for the **coronavirus** package to check for updates on the dev version and install it if need (reinstall the package from Github).

Here is the function docs - https://ramikrispin.github.io/coronavirus/reference/update_datasets.html
