### ISSUE TITLE
Error running the dashboard on my Shinyserver

### ISSUE THREAD

**Issue by pasmer** [RamiKrispin/coronavirus_dashboard#7]
Hi Rami,
I forked your dashboard on my R server/Shiny.
I'm trying to run your dashboard but I got an error here in my shiny log:

---
su: ignoring --preserve-environment, it's mutually exclusive with --login

Listening on http://127.0.0.1:39235
Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'leaflet-providers-1.9.0'; `directoryPath` = '/tmp/RtmpFpS8yQ'
  108: stop
  107: value[[3L]]
  106: tryCatchOne
  105: tryCatchList
  104: tryCatch
  103: addResourcePath
  102: FUN
  101: lapply
  100: processDeps
   99: transform
   98: func
   96: f
   95: Reduce
   86: do
   85: hybrid_chain
   84: origRenderFunc
   83: output$__reactivedoc__
    3: <Anonymous>
    1: rmarkdown::run

Have you any suggestion?
Thanks
Pasquale

ps. Stay safe

**Comment by RamiKrispin** [comment]
This seems coming from the map object, but not sure what is causing it. Here is some similar issue:
https://github.com/rstudio/leaflet/issues/664
https://github.com/cywhale/ODB/issues/5

Check Joe Cheng suggestions about how to handle the leaflet object, that might help

**Comment by pasmer** [comment]
> This seems coming from the map object, but not sure what is causing it. Here is some similar issue:
> [rstudio/leaflet#664](https://github.com/rstudio/leaflet/issues/664)
> [cywhale/ODB#5](https://github.com/cywhale/ODB/issues/5)
> 
> Check Joe Cheng suggestions about how to handle the leaflet object, that might help

Thanks for the suggestion.
I've almost understood the issue.
But my question is: following the Joe Cheng's suggestions I need to change some part of your code?

**Comment by RamiKrispin** [comment]
It is hard for me to answer it without seeing the code, do you have a reproducible code?

**Comment by pasmer** [comment]
> It is hard for me to answer it without seeing the code, do you have a reproducible code?

Well, I've just clone your code and deployed in my raspberry pi Shiny R-server. I guess the problem was related to some updates to do with other packages like tibble.
Now all is fine but the update of the daily data is not automatic.

Thanks for all and congrats for your work!
