### ISSUE TITLE
Death rate for closed cases not obvious in the dashboard application.

### ISSUE THREAD

**Issue by truedeity** [RamiKrispin/coronavirus_dashboard#8]
The dashboard application is great for showing the death rate based on the total number of cases.  But it is not so great at showing the death rate for the closed number of cases...

Closed Cases = Deaths + Recoveries

The total number of cases includes individuals who are still sick and I don't want to see the data that includes outcomes that are still pending.  So I would like to suggest adding two possible options for visualizing the death rate:

Option 1 shows mortality rate for total cases. i.e. (Deaths / Confirmed cases) * 100 
Option 2 shows mortality rate for closed cases i.e. (Deaths / Closed Cases ) * 100

Should be able to achieve Option 2 by eliminating all of the Active cases.  Also, it would also be nice to see that data without China.

**Comment by RamiKrispin** [comment]
Hi @truedeity sorry for the late response, I missed this issue. 

Thanks for the suggestions, I will try to incorporate on the next refresh of the dashboard. 

Best,
Rami
